spring.datasource.url=jdbc:mysql://localhost:3306/timer_db?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

kakao.client-id=9b2b9bfa5edfe658b4281a52fb33a0fe
kakao.redirect-uri=http://localhost:8080/login/oauth2/code/kakao

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true